linters:
  PropertySortOrder:
    enabled: true
    ignore_unspecified: false
    min_properties: 2
    separate_groups: false
    order: concentric
  LeadingZero:
    enabled: true
    style: include_zero # or 'exclude_zero'
  Comment:
    enabled: false
    style: silent
