# Site settings
title: Drop In
baseurl: "/drop-in-marketing-site" # the subpath of your site, e.g. /blog
url: "REPLACE_ME" # the base hostname & protocol for your site

twitter:
facebook:
instagram:
mailchimp: #visible


# Build settings
markdown: kramdown
